const leaders = [
  {
    developer_name: "LucidTrades",
    pDeveloperAlias: "LucidTrades",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "61.87",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+160.6%</span>',
    isTOS: "186174",
    numtrades: "396",
    tradesFutures: 1,
    jSharpe: "3.62",
    featured_extra_info_text_multiline: null,
    numlast180: "36.3",
    maxDDpercent: "11.6",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140372245",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "190.37",
    profitFactor: "1.893",
    pSystemAdded: "May 04, 2022",
    maxdrawdownPcnt: "11.56",
    last90: '<span class="pos">+14.3%</span>',
    numlast30: "0.7",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.97",
    unitSize: 30000,
    ownerAutoTrades: "186174",
    noRasterizedHypo: 0,
    developerUserID: "140370396",
    online: 0,
    startingcash: "10000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 99,
    chartClass: null,
    c2_system_score: "999",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$30,000",
    numSubsNow: "124",
    isSimAvailable: 1,
    last30: '<span class="pos">+0.7%</span>',
    isSelected: 0,
    numlast90: "14.3",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+36.3%</span>',
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "102",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 1,
    tradesForex: 0,
    developer_from: null,
    systemname: "LUCIDMNQ",
    scaledRisk: 1,
    rawSubMonthly: "149",
    pSystemName: "LUCIDMNQ",
    icon_is_default: 0,
    developer_name_length: 11,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$149 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "632",
    CHARTHEIGHT: null,
    NFAreturnnum: "160.6",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "10.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "LucidTrades",
  },
  {
    developer_name: "PeterAlexanderr",
    pDeveloperAlias: "PeterAlexanderr",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "56.08",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+33.9%</span>',
    isTOS: "0",
    numtrades: "148",
    tradesFutures: 1,
    jSharpe: "3.35",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "3.2",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140732252",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "153.67",
    profitFactor: "2.492",
    pSystemAdded: "Jun 10, 2022",
    maxdrawdownPcnt: "3.16",
    last90: '<span class="pos">+10.3%</span>',
    numlast30: "2.1",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.17",
    unitSize: 60000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "130958775",
    online: 0,
    startingcash: "42500",
    featured_extra_info_present: null,
    c2star_status: "2",
    complement_scaledRisk: 99,
    chartClass: null,
    c2_system_score: "998",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$60,000",
    numSubsNow: "11",
    isSimAvailable: 1,
    last30: '<span class="pos">+2.1%</span>',
    isSelected: 0,
    numlast90: "10.3",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "de",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "9",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 0,
    tradesForex: 0,
    developer_from: null,
    systemname: "SlowTrade",
    scaledRisk: 1,
    rawSubMonthly: "125",
    pSystemName: "SlowTrade",
    icon_is_default: 1,
    developer_name_length: 15,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$125 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "124",
    CHARTHEIGHT: null,
    NFAreturnnum: "33.9",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "0.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "PeterAlexanderr",
  },
  {
    developer_name: "TingYu",
    pDeveloperAlias: "TingYu",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "60.74",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+37.2%</span>',
    isTOS: "0",
    numtrades: "163",
    tradesFutures: 1,
    jSharpe: "3.56",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "9.5",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140568818",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "171.53",
    profitFactor: "2.046",
    pSystemAdded: "May 23, 2022",
    maxdrawdownPcnt: "9.5",
    last90: '<span class="pos">+10.1%</span>',
    numlast30: "1.5",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.17",
    unitSize: 50000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "137280768",
    online: 0,
    startingcash: "38700",
    featured_extra_info_present: null,
    c2star_status: "2",
    complement_scaledRisk: 99,
    chartClass: null,
    c2_system_score: "996",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$50,000",
    numSubsNow: "6",
    isSimAvailable: 1,
    last30: '<span class="pos">+1.5%</span>',
    isSelected: 0,
    numlast90: "10.1",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "de",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "2",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 1,
    tradesForex: 0,
    developer_from: "De",
    systemname: "CBOT trade",
    scaledRisk: 1,
    rawSubMonthly: "125",
    pSystemName: "CBOT trade",
    icon_is_default: 0,
    developer_name_length: 6,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$125 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "114",
    CHARTHEIGHT: null,
    NFAreturnnum: "37.2",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "0.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "TingYu",
  },
  {
    developer_name: "AndySong",
    pDeveloperAlias: "AndySong",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "44.44",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+48.1%</span>',
    isTOS: "0",
    numtrades: "36",
    tradesFutures: 0,
    jSharpe: "1.84",
    featured_extra_info_text_multiline: null,
    numlast180: "28.4",
    maxDDpercent: "20.9",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "139682545",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "248.5",
    profitFactor: "2.062",
    pSystemAdded: "Mar 07, 2022",
    maxdrawdownPcnt: "20.92",
    last90: '<span class="pos">+29.8%</span>',
    numlast30: "12.1",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "2.67",
    unitSize: 5000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "126307256",
    online: 1,
    startingcash: "25000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 95,
    chartClass: null,
    c2_system_score: "995",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$5,000",
    numSubsNow: "6",
    isSimAvailable: 1,
    last30: '<span class="pos">+12.1%</span>',
    isSelected: 0,
    numlast90: "29.8",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+28.4%</span>',
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "2",
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 0,
    tradesForex: 0,
    developer_from: "USA",
    systemname: "Tesla S",
    scaledRisk: "5",
    rawSubMonthly: "80",
    pSystemName: "Tesla S",
    icon_is_default: 0,
    developer_name_length: 8,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$80 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "51",
    CHARTHEIGHT: null,
    NFAreturnnum: "48.1",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "205.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "AndySong",
  },
  {
    developer_name: "KINETIC",
    pDeveloperAlias: "KINETIC",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "54.76",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+110.7%</span>',
    isTOS: "0",
    numtrades: "294",
    tradesFutures: 0,
    jSharpe: "2.8",
    featured_extra_info_text_multiline: null,
    numlast180: "118.0",
    maxDDpercent: "19.6",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140368689",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "190.51",
    profitFactor: "1.679",
    pSystemAdded: "May 04, 2022",
    maxdrawdownPcnt: "19.63",
    last90: '<span class="pos">+23.9%</span>',
    numlast30: "7.1",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.97",
    unitSize: 35000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "140368325",
    online: 0,
    startingcash: "10000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 95,
    chartClass: null,
    c2_system_score: "994",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$35,000",
    numSubsNow: "16",
    isSimAvailable: 1,
    last30: '<span class="pos">+7.1%</span>',
    isSelected: 0,
    numlast90: "23.9",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+118.0%</span>',
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "10",
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 1,
    tradesForex: 0,
    developer_from: "USA",
    systemname: "THEGOAT",
    scaledRisk: "5",
    rawSubMonthly: "149",
    pSystemName: "THEGOAT",
    icon_is_default: 0,
    developer_name_length: 7,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$149 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "263",
    CHARTHEIGHT: null,
    NFAreturnnum: "110.7",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "225.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "KINETIC",
  },
  {
    developer_name: "Algoteam-1",
    pDeveloperAlias: "Algoteam-1",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "49.86",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+89.1%</span>',
    isTOS: "0",
    numtrades: "346",
    tradesFutures: 1,
    jSharpe: "1.93",
    featured_extra_info_text_multiline: null,
    numlast180: "30.8",
    maxDDpercent: "17.0",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "139232865",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "280.64",
    profitFactor: "1.332",
    pSystemAdded: "Feb 03, 2022",
    maxdrawdownPcnt: "17.03",
    last90: '<span class="pos">+29.4%</span>',
    numlast30: "15.2",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "16.67",
    unitSize: 100000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "128635951",
    online: 0,
    startingcash: "60000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 90,
    chartClass: null,
    c2_system_score: "993",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$100,000",
    numSubsNow: "3",
    isSimAvailable: 1,
    last30: '<span class="pos">+15.2%</span>',
    isSelected: 0,
    numlast90: "29.4",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "mk",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+30.8%</span>',
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "3",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 0,
    tradesForex: 0,
    developer_from: "Mk",
    systemname: "Falang",
    scaledRisk: "10",
    rawSubMonthly: "500",
    pSystemName: "Falang",
    icon_is_default: 0,
    developer_name_length: 10,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$500 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "29",
    CHARTHEIGHT: null,
    NFAreturnnum: "89.1",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "430.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "Algoteam-1",
  },
  {
    developer_name: "VIXPro",
    pDeveloperAlias: "VIXPro",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "49.85",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+63.0%</span>',
    isTOS: "0",
    numtrades: "341",
    tradesFutures: 1,
    jSharpe: "1.14",
    featured_extra_info_text_multiline: null,
    numlast180: "35.5",
    maxDDpercent: "28.9",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "133141816",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "676.32",
    profitFactor: "1.439",
    pSystemAdded: "Jan 03, 2021",
    maxdrawdownPcnt: "28.93",
    last90: '<span class="pos">+3.9%</span>',
    numlast30: "-0.0",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "6.50",
    unitSize: 60000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "124998479",
    online: 0,
    startingcash: "25000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 83,
    chartClass: null,
    c2_system_score: "992",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$60,000",
    numSubsNow: "1",
    isSimAvailable: 1,
    last30: "-0.0%",
    isSelected: 0,
    numlast90: "3.9",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 1,
    developer_country_code: "be",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+35.5%</span>',
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    hide_developer_names: 0,
    tradesWhat: " Stocks",
    even: 1,
    tradesForex: 0,
    developer_from: null,
    systemname: "VIXPro Volatility Fund",
    scaledRisk: "17",
    rawSubMonthly: "195",
    pSystemName: "VIXPro Volatility Fund",
    icon_is_default: 0,
    developer_name_length: 6,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$195 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "53",
    CHARTHEIGHT: null,
    NFAreturnnum: "63.0",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "730.00",
    NFAreturnLabel: "Annual Return",
    developerAlias: "VIXPro",
  },
  {
    developer_name: "MarkAnderson4",
    pDeveloperAlias: "MarkAnderson4",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "64.91",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+54.7%</span>',
    isTOS: "0",
    numtrades: "114",
    tradesFutures: 1,
    jSharpe: "1.85",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "30.4",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140757086",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "150.28",
    profitFactor: "1.865",
    pSystemAdded: "Jun 13, 2022",
    maxdrawdownPcnt: "30.43",
    last90: '<span class="pos">+62.8%</span>',
    numlast30: "1.7",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.97",
    unitSize: 100000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "129689070",
    online: 0,
    startingcash: "100000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 83,
    chartClass: null,
    c2_system_score: "990",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$100,000",
    numSubsNow: "1",
    isSimAvailable: 1,
    last30: '<span class="pos">+1.7%</span>',
    isSelected: 0,
    numlast90: "62.8",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 0,
    tradesForex: 0,
    developer_from: null,
    systemname: "Ascend",
    scaledRisk: "17",
    rawSubMonthly: "149",
    pSystemName: "Ascend",
    icon_is_default: 0,
    developer_name_length: 13,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$149 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "5",
    CHARTHEIGHT: null,
    NFAreturnnum: "54.7",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "755.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "MarkAnderson4",
  },
  {
    developer_name: "TradePath",
    pDeveloperAlias: "TradePath",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "81.09",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+283.2%</span>',
    isTOS: "0",
    numtrades: "201",
    tradesFutures: 1,
    jSharpe: "2.97",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "40.4",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140513851",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "176.8",
    profitFactor: "5.275",
    pSystemAdded: "May 18, 2022",
    maxdrawdownPcnt: "40.44",
    last90: '<span class="pos">+244.8%</span>',
    numlast30: "28.6",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "7.63",
    unitSize: 80000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "134180077",
    online: 0,
    startingcash: "25000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 78,
    chartClass: null,
    c2_system_score: "989",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$80,000",
    numSubsNow: "3",
    isSimAvailable: 1,
    last30: '<span class="pos">+28.6%</span>',
    isSelected: 0,
    numlast90: "244.8",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "4",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 1,
    tradesForex: 0,
    developer_from: "Oakland, USA",
    systemname: "TradeDetector",
    scaledRisk: "22",
    rawSubMonthly: "229",
    pSystemName: "TradeDetector",
    icon_is_default: 0,
    developer_name_length: 9,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$229 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "129",
    CHARTHEIGHT: null,
    NFAreturnnum: "283.2",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "965.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "TradePath",
  },
  {
    developer_name: "Sr_Ne",
    pDeveloperAlias: "Sr_Ne",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "53.23",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+52.3%</span>',
    isTOS: "0",
    numtrades: "124",
    tradesFutures: 0,
    jSharpe: "2.34",
    featured_extra_info_text_multiline: null,
    numlast180: "52.7",
    maxDDpercent: "13.2",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140477271",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "180.02",
    profitFactor: "1.76",
    pSystemAdded: "May 15, 2022",
    maxdrawdownPcnt: "13.16",
    last90: '<span class="pos">+5.2%</span>',
    numlast30: "-1.6",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "10.00",
    unitSize: 35000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "139184212",
    online: 0,
    startingcash: "50000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 96,
    chartClass: null,
    c2_system_score: "988",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$35,000",
    numSubsNow: "5",
    isSimAvailable: 1,
    last30: '<span class="neg">-1.6%</span>',
    isSelected: 0,
    numlast90: "5.2",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 1,
    developer_country_code: "in",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+52.7%</span>',
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "1",
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 0,
    tradesForex: 0,
    developer_from: "In",
    systemname: "Ha Algorithmic Trading",
    scaledRisk: "4",
    rawSubMonthly: "300",
    pSystemName: "Ha Algorithmic Trading",
    icon_is_default: 0,
    developer_name_length: 5,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$300 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "155",
    CHARTHEIGHT: null,
    NFAreturnnum: "52.3",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "180.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "Sr_Ne",
  },
  {
    developer_name: "Seikh",
    pDeveloperAlias: "Seikh",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "45.42",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+81.1%</span>',
    isTOS: "0",
    numtrades: "2466",
    tradesFutures: 0,
    jSharpe: "1.14",
    featured_extra_info_text_multiline: null,
    numlast180: "10.5",
    maxDDpercent: "60.7",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "138580546",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "331.43",
    profitFactor: "1.186",
    pSystemAdded: "Dec 14, 2021",
    maxdrawdownPcnt: "60.68",
    last90: '<span class="pos">+5.8%</span>',
    numlast30: "22.1",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.17",
    unitSize: 35000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "136603502",
    online: 0,
    startingcash: "45000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 73,
    chartClass: null,
    c2_system_score: "987",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$35,000",
    numSubsNow: "1",
    isSimAvailable: 1,
    last30: '<span class="pos">+22.1%</span>',
    isSelected: 0,
    numlast90: "5.8",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "ee",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+10.5%</span>',
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "2",
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 1,
    tradesForex: 0,
    developer_from: "Ee",
    systemname: "Stocks to daytrade",
    scaledRisk: "27",
    rawSubMonthly: "125",
    pSystemName: "Stocks to daytrade",
    icon_is_default: 1,
    developer_name_length: 5,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$125 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "18",
    CHARTHEIGHT: null,
    NFAreturnnum: "81.1",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "1160.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "Seikh",
  },
  {
    developer_name: "JohnBennett",
    pDeveloperAlias: "JohnBennett",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "53.94",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+39.8%</span>',
    isTOS: "0",
    numtrades: "977",
    tradesFutures: 0,
    jSharpe: "1.64",
    featured_extra_info_text_multiline: null,
    numlast180: "-2.0",
    maxDDpercent: "13.4",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "128743489",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "928.26",
    profitFactor: "1.326",
    pSystemAdded: "Apr 26, 2020",
    maxdrawdownPcnt: "13.38",
    last90: '<span class="neg">-0.6%</span>',
    numlast30: "1.8",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "6.67",
    unitSize: 35000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "24088430",
    online: 0,
    startingcash: "100000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 97,
    chartClass: null,
    c2_system_score: "986",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$35,000",
    numSubsNow: "17",
    isSimAvailable: 1,
    last30: '<span class="pos">+1.8%</span>',
    isSelected: 0,
    numlast90: "-0.6",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 1,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="neg">-2.0%</span>',
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "18",
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 0,
    tradesForex: 0,
    developer_from: "Matthews, USA",
    systemname: "JWB Stock and ETF ORB",
    scaledRisk: "3",
    rawSubMonthly: "200",
    pSystemName: "JWB Stock and ETF ORB",
    icon_is_default: 0,
    developer_name_length: 11,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$200 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "34",
    CHARTHEIGHT: null,
    NFAreturnnum: "39.8",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "110.00",
    NFAreturnLabel: "Annual Return",
    developerAlias: "JohnBennett",
  },
  {
    developer_name: "MarkAnderson4",
    pDeveloperAlias: "MarkAnderson4",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "61.56",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+76.6%</span>',
    isTOS: "0",
    numtrades: "307",
    tradesFutures: 1,
    jSharpe: "1.57",
    featured_extra_info_text_multiline: null,
    numlast180: "30.4",
    maxDDpercent: "45.9",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "139866386",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "234.28",
    profitFactor: "1.508",
    pSystemAdded: "Mar 21, 2022",
    maxdrawdownPcnt: "45.89",
    last90: '<span class="pos">+66.7%</span>',
    numlast30: "4.7",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "3.33",
    unitSize: 90000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "129689070",
    online: 0,
    startingcash: "50000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 79,
    chartClass: null,
    c2_system_score: "984",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$90,000",
    numSubsNow: "1",
    isSimAvailable: 1,
    last30: '<span class="pos">+4.7%</span>',
    isSelected: 0,
    numlast90: "66.7",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+30.4%</span>',
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "1",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 1,
    tradesForex: 0,
    developer_from: null,
    systemname: "Velocity 1",
    scaledRisk: "21",
    rawSubMonthly: "100",
    pSystemName: "Velocity 1",
    icon_is_default: 0,
    developer_name_length: 13,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$100 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "64",
    CHARTHEIGHT: null,
    NFAreturnnum: "76.6",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "925.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "MarkAnderson4",
  },
  {
    developer_name: "FXAMK",
    pDeveloperAlias: "FXAMK",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "63.9",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+7.3%</span>',
    isTOS: "0",
    numtrades: "349",
    tradesFutures: 0,
    jSharpe: "3.01",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "1.7",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "141015323",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "122.98",
    profitFactor: "1.881",
    pSystemAdded: "Jul 10, 2022",
    maxdrawdownPcnt: "1.73",
    last90: '<span class="pos">+4.9%</span>',
    numlast30: "3.5",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.17",
    unitSize: 100000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "139140162",
    online: 0,
    startingcash: "250000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 99,
    chartClass: null,
    c2_system_score: "983",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$100,000",
    numSubsNow: "1",
    isSimAvailable: 1,
    last30: '<span class="pos">+3.5%</span>',
    isSelected: 0,
    numlast90: "4.9",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    hide_developer_names: 0,
    tradesWhat: "Forex",
    even: 0,
    tradesForex: 1,
    developer_from: "West Hills, USA",
    systemname: "FXFMKL",
    scaledRisk: 1,
    rawSubMonthly: "125",
    pSystemName: "FXFMKL",
    icon_is_default: 0,
    developer_name_length: 5,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$125 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "2",
    CHARTHEIGHT: null,
    NFAreturnnum: "7.3",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "0.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "FXAMK",
  },
  {
    developer_name: "CNV-Trading",
    pDeveloperAlias: "CNV-Trading",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "78.57",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+45.6%</span>',
    isTOS: "0",
    numtrades: "42",
    tradesFutures: 0,
    jSharpe: "1.54",
    featured_extra_info_text_multiline: null,
    numlast180: "28.7",
    maxDDpercent: "17.2",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "138034854",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "374.43",
    profitFactor: "5.3",
    pSystemAdded: "Nov 01, 2021",
    maxdrawdownPcnt: "17.25",
    last90: '<span class="pos">+19.7%</span>',
    numlast30: "17.0",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "5.83",
    unitSize: 15000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "138002443",
    online: 0,
    startingcash: "10000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 99,
    chartClass: null,
    c2_system_score: "982",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$15,000",
    numSubsNow: "4",
    isSimAvailable: 1,
    last30: '<span class="pos">+17.0%</span>',
    isSelected: 0,
    numlast90: "19.7",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "be",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+28.7%</span>',
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 1,
    tradesForex: 0,
    developer_from: null,
    systemname: "Sapphire",
    scaledRisk: "1",
    rawSubMonthly: "175",
    pSystemName: "Sapphire",
    icon_is_default: 0,
    developer_name_length: 11,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$175 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "1",
    CHARTHEIGHT: null,
    NFAreturnnum: "45.6",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "50.00",
    NFAreturnLabel: "Annual Return",
    developerAlias: "CNV-Trading",
  },
  {
    developer_name: "DaurenBadayev",
    pDeveloperAlias: "DaurenBadayev",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "73.28",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+98.3%</span>',
    isTOS: "0",
    numtrades: "116",
    tradesFutures: 0,
    jSharpe: "2.32",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "29.8",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140966856",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "128.44",
    profitFactor: "1.544",
    pSystemAdded: "Jul 05, 2022",
    maxdrawdownPcnt: "29.84",
    last90: '<span class="pos">+28.0%</span>',
    numlast30: "-9.2",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "3.30",
    unitSize: 35000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "140957053",
    online: 0,
    startingcash: "25000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 79,
    chartClass: null,
    c2_system_score: "981",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$35,000",
    numSubsNow: "7",
    isSimAvailable: 1,
    last30: '<span class="neg">-9.2%</span>',
    isSelected: 0,
    numlast90: "28.0",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 1,
    developer_country_code: "kz",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "2",
    hide_developer_names: 0,
    tradesWhat: "Stocks",
    even: 0,
    tradesForex: 0,
    developer_from: null,
    systemname: "Momentum Front Running",
    scaledRisk: "21",
    rawSubMonthly: "99",
    pSystemName: "Momentum Front Running",
    icon_is_default: 0,
    developer_name_length: 13,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$99 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "66",
    CHARTHEIGHT: null,
    NFAreturnnum: "98.3",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "940.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "DaurenBadayev",
  },
  {
    developer_name: "MarkAnderson4",
    pDeveloperAlias: "MarkAnderson4",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "61.33",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+61.4%</span>',
    isTOS: "0",
    numtrades: "75",
    tradesFutures: 1,
    jSharpe: "2.72",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "14.6",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140862065",
    tradesStocks: 1,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "138.3",
    profitFactor: "2.325",
    pSystemAdded: "Jun 25, 2022",
    maxdrawdownPcnt: "14.62",
    last90: '<span class="pos">+54.5%</span>',
    numlast30: "16.6",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "3.30",
    unitSize: 90000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "129689070",
    online: 0,
    startingcash: "51000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 92,
    chartClass: null,
    c2_system_score: "980",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$90,000",
    numSubsNow: "5",
    isSimAvailable: 1,
    last30: '<span class="pos">+16.6%</span>',
    isSelected: 0,
    numlast90: "54.5",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "4",
    hide_developer_names: 0,
    tradesWhat: " Futures",
    even: 1,
    tradesForex: 0,
    developer_from: null,
    systemname: "SP500 VIX",
    scaledRisk: "8",
    rawSubMonthly: "99",
    pSystemName: "SP500 VIX",
    icon_is_default: 0,
    developer_name_length: 13,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$99 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "42",
    CHARTHEIGHT: null,
    NFAreturnnum: "61.4",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "330.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "MarkAnderson4",
  },
  {
    developer_name: "PeterAlexanderr",
    pDeveloperAlias: "PeterAlexanderr",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "52.56",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+92.5%</span>',
    isTOS: "0",
    numtrades: "430",
    tradesFutures: 1,
    jSharpe: "1.18",
    featured_extra_info_text_multiline: null,
    numlast180: "103.3",
    maxDDpercent: "61.3",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "134255487",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "624.62",
    profitFactor: "1.511",
    pSystemAdded: "Feb 24, 2021",
    maxdrawdownPcnt: "61.28",
    last90: '<span class="pos">+13.5%</span>',
    numlast30: "10.1",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "5.00",
    unitSize: 70000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "130958775",
    online: 0,
    startingcash: "23844",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 81,
    chartClass: null,
    c2_system_score: "978",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$70,000",
    numSubsNow: "6",
    isSimAvailable: 1,
    last30: '<span class="pos">+10.1%</span>',
    isSelected: 0,
    numlast90: "13.5",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "de",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+103.3%</span>',
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "2",
    hide_developer_names: 0,
    tradesWhat: "Futures, Forex",
    even: 0,
    tradesForex: 1,
    developer_from: null,
    systemname: "Just E mini SP500",
    scaledRisk: "19",
    rawSubMonthly: "150",
    pSystemName: "Just E mini SP500",
    icon_is_default: 1,
    developer_name_length: 15,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$150 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "153",
    CHARTHEIGHT: null,
    NFAreturnnum: "92.5",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "845.00",
    NFAreturnLabel: "Annual Return",
    developerAlias: "PeterAlexanderr",
  },
  {
    developer_name: "TingYu",
    pDeveloperAlias: "TingYu",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "62.14",
    tradesOptions: 0,
    NFAreturn: '<span class="pos">+27.3%</span>',
    isTOS: "0",
    numtrades: "140",
    tradesFutures: 1,
    jSharpe: "2.85",
    featured_extra_info_text_multiline: null,
    numlast180: null,
    maxDDpercent: "4.9",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140568873",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "171.52",
    profitFactor: "2.143",
    pSystemAdded: "May 23, 2022",
    maxdrawdownPcnt: "4.87",
    last90: '<span class="pos">+5.8%</span>',
    numlast30: "-3.8",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "4.17",
    unitSize: 50000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "137280768",
    online: 0,
    startingcash: "42500",
    featured_extra_info_present: null,
    c2star_status: "2",
    complement_scaledRisk: 99,
    chartClass: null,
    c2_system_score: "976",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$50,000",
    numSubsNow: "7",
    isSimAvailable: 1,
    last30: '<span class="neg">-3.8%</span>',
    isSelected: 0,
    numlast90: "5.8",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "de",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: "-",
    show_developer_from: 1,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "4",
    hide_developer_names: 0,
    tradesWhat: "Futures",
    even: 1,
    tradesForex: 0,
    developer_from: "De",
    systemname: "Faith Trend",
    scaledRisk: 1,
    rawSubMonthly: "125",
    pSystemName: "Faith Trend",
    icon_is_default: 0,
    developer_name_length: 6,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$125 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "139",
    CHARTHEIGHT: null,
    NFAreturnnum: "27.3",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "0.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "TingYu",
  },
  {
    developer_name: "High-Frequency-Algo",
    pDeveloperAlias: "High-Frequency-Algo",
    hide_put_in_basket_plus_icon: 1,
    percentWinPositions: "60.22",
    tradesOptions: 1,
    NFAreturn: '<span class="pos">+1668.3%</span>',
    isTOS: "0",
    numtrades: "181",
    tradesFutures: 0,
    jSharpe: "3.45",
    featured_extra_info_text_multiline: null,
    numlast180: "160.2",
    maxDDpercent: "40.1",
    hidden_based_on_initial_instru_filter: 0,
    CHARTWIDTH: null,
    systemid: "140022552",
    tradesStocks: 0,
    freeTrialDays: "0",
    no_monthly_subs: 0,
    systemAgeDays: "220.46",
    profitFactor: "2.755",
    pSystemAdded: "Apr 04, 2022",
    maxdrawdownPcnt: "40.12",
    last90: '<span class="pos">+63.2%</span>',
    numlast30: "4.7",
    no_free_trials_for_subs_started_here: "1",
    rawSubDaily: "3.33",
    unitSize: 35000,
    ownerAutoTrades: "0",
    noRasterizedHypo: 0,
    developerUserID: "136919774",
    online: 0,
    startingcash: "50000",
    featured_extra_info_present: null,
    c2star_status: "0",
    complement_scaledRisk: 80,
    chartClass: null,
    c2_system_score: "975",
    dev_name_long: 0,
    hide_c2star_status: null,
    pUnitSize: "$35,000",
    numSubsNow: "19",
    isSimAvailable: 1,
    last30: '<span class="pos">+4.7%</span>',
    isSelected: 0,
    numlast90: "63.2",
    bestSiteName: "C2",
    isProPlan: 0,
    sys_name_long: 0,
    developer_country_code: "us",
    ccRequired: 1,
    noSlotsAvailable: 0,
    last180: '<span class="pos">+160.2%</span>',
    show_developer_from: 0,
    isRealPrivatePlatform: 0,
    ageDays: null,
    numLiveATaccts: "23",
    hide_developer_names: 0,
    tradesWhat: " Options",
    even: 0,
    tradesForex: 0,
    developer_from: null,
    systemname: "High Frequency Algo",
    scaledRisk: "20",
    rawSubMonthly: "100",
    pSystemName: "High Frequency Algo",
    icon_is_default: 0,
    developer_name_length: 19,
    featured_extra_info_text_oneline: null,
    subscribePrice: "$100 /mo.",
    hide_sub_cost: 0,
    numAutoTraders: "115",
    CHARTHEIGHT: null,
    NFAreturnnum: "1668.3",
    reducedTrialToZero: 0,
    hide_developer_images: 0,
    rawRisk: "870.00",
    NFAreturnLabel: "Cumul. Return",
    developerAlias: "High-Frequency-Algo",
  },
];
